from .dino_loss import DINOLoss
from .feature_loss import FeatureLoss
from .gpt_sparse_loss import GPTSparseLoss
from .nextwp_loss import NextWPLoss
from .timeemb_loss import TimeEmbLoss
from .dinoknn_loss import DINOKNNLoss
from .timeavr_loss import TimeAvrLoss
from .dino_mi_loss import DINOMILoss
from .dino_mi2_loss import DINOMI2Loss
